"""
Alert and Anomaly Models for Lectio

This module defines the data models for anomaly alerts and severity levels
used by the anomaly detection engine.

Author: Lectio Backend Team
Version: 4.0.0
"""

from enum import Enum
from typing import Optional
from datetime import datetime, timezone

from beanie import Document, Indexed
from beanie.odm.fields import PydanticObjectId
from pydantic import Field


class AlertSeverity(str, Enum):
    """Severity levels for anomaly alerts."""
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AnomalyAlertDocument(Document):
    """
    Anomaly alert document for persistent storage of detected anomalies.
    
    This model stores alerts generated by the anomaly engine when telemetry
    metrics breach defined thresholds. All queries enforce multi-tenant
    isolation through user_id and device_id filtering.
    """
    user_id: Indexed(PydanticObjectId, description="Reference to the User for tenant isolation")
    device_id: Indexed(PydanticObjectId, description="Reference to the Device")
    rule_name: str = Field(..., min_length=1, max_length=128, description="Name of the rule that triggered this alert")
    severity: AlertSeverity = Field(..., description="Severity level of the alert")
    metric_name: str = Field(..., min_length=1, max_length=64, description="Name of the metric that breached the threshold")
    trigger_value: float = Field(..., description="The actual value that triggered the alert")
    threshold_limit: float = Field(..., description="The threshold value that was breached")
    message: str = Field(..., min_length=1, max_length=512, description="Human-readable alert message")
    is_active: bool = Field(default=True, description="Whether the alert is currently active")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Alert creation timestamp")
    resolved_at: Optional[datetime] = Field(None, description="Alert resolution timestamp (when is_active becomes False)")
    
    class Settings:
        name = "anomaly_alerts"
        indexes = [
            "user_id",
            "device_id",
            "rule_name",
            "severity",
            "is_active",
            "created_at",
        ]
